version: '3.9'
services:
  web:
    image: nginx:stable-alpine
    container_name: web
    restart: unless-stopped
    expose:
      - 9003
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    volumes:
      - ${SOURCE_PATH}:/var/www/html
    networks:
      localhost:
        ipv4_address: 172.19.0.1
        aliases:
          - ${LOCALHOST}
networks:
  localhost:
      driver: bridge
      name: localhost
      ipam:
          driver: default
          config:
              - subnet: 172.19.0.5/16